[book]
authors = ["a-boy"]
language = "zh"
multilingual = false
src = "src"
title = "纯部碎页"
description = "零碎稿件中心"

[build]
build-dir = "docs"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/qingtk/leaf"
edit-url-template = "https://github.com/qingtk/leaf/edit/main/{path}"
site-url = "/leaf/"


